import { Car, CookingPot, Flower2, Search, ShoppingBag, ShoppingBasket, Sparkles, Store, UtensilsCrossed, WashingMachine, Wrench, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { sectorCatalog } from "@shared/sectorCatalog";

type SectorCard = { slug: string; labelAr: string; labelEn: string; labelFr: string; icon: LucideIcon; color: string; listingCount: number; imageUrl?: string | null };
const icons: Record<string, LucideIcon> = { restaurant: UtensilsCrossed, fashion: ShoppingBag, beauty_salon: Flower2, grocery: ShoppingBasket, vegetables: CookingPot, laundry: WashingMachine, automotive: Car, public_works: Wrench, trend: Sparkles, other: Store };
const fallbackImages: Record<string, string> = { restaurant: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&h=900&q=80", fashion: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&h=900&q=80", beauty_salon: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&h=900&q=80", grocery: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&h=900&q=80", vegetables: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&h=900&q=80", laundry: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=900&h=900&q=80", automotive: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&h=900&q=80", public_works: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&h=900&q=80", trend: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&h=900&q=80", other: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&h=900&q=80" };
const fallbackSectors: SectorCard[] = sectorCatalog.map((sector) => ({ slug: sector.slug, labelAr: sector.labelAr, labelEn: sector.labelEn, labelFr: sector.labelFr, icon: icons[sector.slug] ?? Store, color: sector.color, imageUrl: fallbackImages[sector.slug], listingCount: 0 }));

export default function MarketplaceLanding() {
  const { language, direction } = useLanguage();
  const [search, setSearch] = useState("");
  const sectorsQuery = trpc.marketplace.publicSectors.useQuery(undefined, { retry: false });
  const storesQuery = trpc.marketplace.publicStores.useQuery({ search: search.trim() || undefined }, { retry: false });
  const liveBySlug = new Map((sectorsQuery.data ?? []).map((sector) => [sector.slug, sector]));
  const rows = fallbackSectors.map((fallback) => ({ ...fallback, ...(liveBySlug.get(fallback.slug) ?? {}), icon: fallback.icon }));
  const query = search.trim().toLowerCase();
  const visibleSectors = query ? rows.filter((sector) => `${sector.labelAr} ${sector.labelEn} ${sector.labelFr}`.toLowerCase().includes(query)) : rows;
  const label = (sector: SectorCard) => language === "ar" ? sector.labelAr : language === "fr" ? sector.labelFr : sector.labelEn;
  const locale = language === "ar" ? "ar-SA" : language === "fr" ? "fr-FR" : "en-US";
  const copy = language === "ar"
    ? { market: "السوق العام", title: "ماذا تبحث عنه اليوم؟", body: "اختر قسمًا واحدًا أو ابحث مباشرة، ثم انتقل إلى المتجر والمنتج بدون خطوات زائدة.", search: "ابحث عن متجر أو منتج أو خدمة…", sectors: "اختر القسم", stores: "متاجر مقترحة", storesEmpty: "لا توجد متاجر منشورة حاليًا.", explore: "عرض المتاجر", items: "عنصر", step1: "1 اختر القسم", step2: "2 اختر المتجر", step3: "3 اطلب أو احجز" }
    : language === "fr"
      ? { market: "Marché général", title: "Que recherchez-vous aujourd’hui ?", body: "Choisissez un secteur ou recherchez directement, puis passez à la boutique sans étapes inutiles.", search: "Rechercher une boutique, un produit ou un service…", sectors: "Choisir un secteur", stores: "Boutiques suggérées", storesEmpty: "Aucune boutique publiée pour le moment.", explore: "Voir les boutiques", items: "éléments", step1: "1 Choisir le secteur", step2: "2 Choisir la boutique", step3: "3 Commander ou réserver" }
      : { market: "General marketplace", title: "What are you looking for today?", body: "Choose one sector or search directly, then move to a store without extra steps.", search: "Search for a store, product, or service…", sectors: "Choose a sector", stores: "Suggested stores", storesEmpty: "No published stores yet.", explore: "View stores", items: "items", step1: "1 Choose sector", step2: "2 Choose store", step3: "3 Order or book" };

  return <main dir={direction} className="min-h-screen bg-[#0b0f17] text-white">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#0b0f17]/95 px-5 py-4 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Link href="/marketplace" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#E76F3C] text-lg font-black">N</span><span><strong className="block tracking-[.12em]">NFOOD</strong><small className="block text-[10px] font-bold text-orange-300/80">{copy.market}</small></span></Link><span className="hidden text-xs font-bold text-slate-400 sm:block">{language === "ar" ? "تجربة شراء بسيطة" : language === "fr" ? "Expérience simple" : "Simple shopping experience"}</span></div>
    </header>
    <section className="relative isolate overflow-hidden px-5 pb-12 pt-14 md:px-8 md:pb-16 md:pt-20"><div className="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-orange-500/20 blur-3xl" /><div className="relative mx-auto max-w-4xl text-center"><div className="mx-auto mb-5 inline-flex items-center gap-2 rounded-full border border-orange-300/30 bg-orange-400/10 px-3 py-2 text-xs font-bold text-orange-200"><Sparkles className="h-4 w-4" /> {copy.market}</div><h1 className="text-4xl font-black leading-tight md:text-6xl">{copy.title}</h1><p className="mx-auto mt-5 max-w-2xl leading-8 text-slate-300">{copy.body}</p><div className="relative mx-auto mt-8 max-w-2xl"><Search className="pointer-events-none absolute right-4 top-3.5 h-5 w-5 text-slate-500" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={copy.search} className="h-13 rounded-2xl border-white/10 bg-white/10 pe-12 text-white placeholder:text-slate-500" /></div><div className="mt-6 flex flex-wrap justify-center gap-2 text-xs font-bold text-slate-400"><span className="rounded-full bg-white/5 px-3 py-2">{copy.step1}</span><span className="rounded-full bg-white/5 px-3 py-2">{copy.step2}</span><span className="rounded-full bg-white/5 px-3 py-2">{copy.step3}</span></div></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-16 md:px-8"><div className="flex items-end justify-between gap-4"><h2 className="text-2xl font-black">{copy.sectors}</h2><span className="text-sm font-bold text-slate-400">{visibleSectors.length}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visibleSectors.map((sector) => { const Icon = sector.icon; const catalog = sectorCatalog.find((item) => item.slug === sector.slug); return <Link key={sector.slug} href={`/marketplace/sector/${sector.slug}`} className="group overflow-hidden rounded-3xl border border-white/10 bg-white/5 transition hover:-translate-y-1 hover:border-orange-400/40"><div className="relative aspect-square overflow-hidden" style={{ background: `linear-gradient(135deg, ${sector.color}bb, #111827)` }}>{sector.imageUrl && <img src={sector.imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover opacity-75 transition duration-300 group-hover:scale-105" loading="lazy" />}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-5"><span className="rounded-full bg-black/20 px-3 py-1 text-[11px] font-bold">{sector.listingCount.toLocaleString(locale)} {copy.items}</span><Icon className="h-7 w-7" /></div></div><div className="p-5"><h3 className="min-h-12 font-black leading-6">{label(sector)}</h3><p className="mt-2 line-clamp-2 min-h-10 text-xs leading-5 text-slate-400">{language === "ar" ? catalog?.descriptionAr : catalog?.labelEn}</p><span className="mt-4 inline-flex text-xs font-bold text-orange-300">{copy.explore} <span className="ms-1 transition group-hover:translate-x-1">→</span></span></div></Link>; })}</div>
      <div className="mt-16"><h2 className="text-2xl font-black">{copy.stores}</h2>{storesQuery.isLoading ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-48 animate-pulse rounded-3xl bg-white/5" />)}</div> : (storesQuery.data ?? []).length === 0 ? <div className="mt-6 rounded-3xl border border-dashed border-white/15 p-12 text-center text-sm text-slate-400">{copy.storesEmpty}</div> : <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(storesQuery.data ?? []).map((store) => <Link key={store.entityId} href={`/store/${store.entityId}`} className="overflow-hidden rounded-3xl border border-white/10 bg-white/5 transition hover:-translate-y-1 hover:border-orange-400/40"><div className="h-20" style={{ background: `linear-gradient(135deg, ${store.restaurant?.brandColor ?? "#162033"}, ${store.restaurant?.brandAccentColor ?? "#334155"})` }} /><div className="p-5"><h3 className="font-black">{store.customerName}</h3><p className="mt-2 text-xs text-slate-400">{store.listingCount} {copy.items}</p></div></Link>)}</div>}</div>
    </section>
  </main>;
}
