import { ArrowLeft, CalendarDays, Clock3, MapPin, Search, ShoppingBag, Star, UtensilsCrossed } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { Link } from "wouter";

const cafes = [
  { name: "مساء كافيه", area: "الرياض · حي النخيل", rating: "4.9", time: "08:00 - 02:00", tag: "الأكثر طلبًا", color: "#d97745", image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=900&q=80" },
  { name: "مقهى الساحة", area: "الرياض · العليا", rating: "4.8", time: "07:00 - 01:00", tag: "قهوة مختصة", color: "#9b6a43", image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80" },
  { name: "جلسة مساء", area: "جدة · الروضة", rating: "4.7", time: "09:00 - 03:00", tag: "جلسات هادئة", color: "#536b68", image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=900&q=80" },
];

const categories = ["الكل", "قهوة مختصة", "حلويات", "فطور", "جلسات", "مشروبات باردة"];

export default function MasaaCafesDemo() {
  const { direction } = useLanguage();
  return <main dir={direction} className="min-h-screen bg-[#f8f5f0] text-[#241c19]">
    <header className="sticky top-0 z-40 border-b border-[#eadfd4] bg-[#fffdf9]/95 px-5 py-4 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#241c19] text-xl font-black text-[#f4b36a]">م</span><span><strong className="block text-lg font-black">مقاهي المساء</strong><small className="block text-[11px] font-bold text-[#a77758]">تجربة المنيو والطلب والحجز</small></span></Link><div className="hidden items-center gap-3 text-sm font-bold text-[#76665d] sm:flex"><a href="#cafes">المقاهي</a><a href="#how">كيف تعمل</a><Link href="/marketplace" className="rounded-xl bg-[#241c19] px-4 py-2 text-white">السوق العام</Link></div></div>
    </header>
    <section className="relative overflow-hidden px-5 pb-14 pt-16 md:pb-20 md:pt-24"><div className="absolute -left-24 -top-24 h-80 w-80 rounded-full bg-[#edb47d]/30 blur-3xl" /><div className="absolute -bottom-36 -right-24 h-96 w-96 rounded-full bg-[#c99d7b]/20 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#d8bda8] bg-white/70 px-4 py-2 text-xs font-black text-[#946444]"><UtensilsCrossed className="h-4 w-4" /> منصة مقاهي المساء · ديمو</div><h1 className="max-w-3xl text-4xl font-black leading-[1.15] md:text-6xl">قهوتك ومزاجك،<br /><span className="text-[#b66f45]">في مكان واحد.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-[#76665d] md:text-lg">اكتشف المقاهي القريبة، تصفح المنيو، احجز جلستك أو اطلب مباشرة — بتجربة بسيطة وسريعة.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#cafes" className="rounded-2xl bg-[#241c19] px-6 py-3.5 text-sm font-black text-white shadow-lg shadow-[#241c19]/15 transition hover:-translate-y-0.5">اكتشف المقاهي</a><a href="#how" className="rounded-2xl border border-[#d8c8bc] bg-white/70 px-6 py-3.5 text-sm font-black text-[#4d3c34]">كيف تعمل؟</a></div><div className="mt-10 flex flex-wrap gap-6 text-sm font-bold text-[#76665d]"><span className="flex items-center gap-2"><ShoppingBag className="h-4 w-4 text-[#b66f45]" /> طلب سريع</span><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#b66f45]" /> حجز جلسة</span><span className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#b66f45]" /> أوقات محدثة</span></div></div><div className="relative overflow-hidden rounded-[2rem] border-8 border-white bg-[#241c19] shadow-2xl shadow-[#5c3d2c]/20"><img src="https://images.unsplash.com/photo-1498804103079-a49436e6c0c3?auto=format&fit=crop&w=1200&q=85" alt="قهوة في مقهى" className="h-[360px] w-full object-cover opacity-90 md:h-[440px]" /><div className="absolute inset-x-5 bottom-5 rounded-2xl border border-white/20 bg-[#241c19]/85 p-4 text-white backdrop-blur-md"><div className="flex items-center justify-between"><div><p className="text-xs text-[#e9b47e]">اختيار اليوم</p><h2 className="mt-1 text-lg font-black">مساء كافيه</h2></div><span className="flex items-center gap-1 rounded-full bg-white/10 px-3 py-1 text-xs font-bold"><Star className="h-3.5 w-3.5 fill-[#f4b36a] text-[#f4b36a]" /> 4.9</span></div><p className="mt-2 text-xs text-white/70">قهوة مختصة · جلسات هادئة · طلب من الطاولة</p></div></div></div></section>
    <section id="cafes" className="mx-auto max-w-7xl px-5 pb-20"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-black text-[#b66f45]">اختَر تجربتك</p><h2 className="mt-2 text-3xl font-black">مقاهي المساء</h2></div><div className="relative w-full max-w-xs"><Search className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-[#a9998e]" /><input placeholder="ابحث عن مقهى…" className="h-10 w-full rounded-xl border border-[#e2d6cc] bg-white px-9 text-sm outline-none focus:border-[#b66f45]" /></div></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{categories.map((category, index) => <button key={category} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black transition ${index === 0 ? "bg-[#241c19] text-white" : "border border-[#e1d4ca] bg-white text-[#76665d] hover:border-[#b66f45]"}`}>{category}</button>)}</div><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{cafes.map((cafe) => <article key={cafe.name} className="group overflow-hidden rounded-3xl border border-[#eadfd4] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-52 overflow-hidden"><img src={cafe.image} alt={cafe.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute right-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-[11px] font-black text-[#5b4539]">{cafe.tag}</span><span className="absolute bottom-4 left-4 flex items-center gap-1 rounded-full bg-[#241c19]/85 px-3 py-1.5 text-xs font-black text-white"><Star className="h-3.5 w-3.5 fill-[#f4b36a] text-[#f4b36a]" /> {cafe.rating}</span></div><div className="p-5"><h3 className="text-xl font-black">{cafe.name}</h3><p className="mt-2 flex items-center gap-1.5 text-xs text-[#88776d]"><MapPin className="h-3.5 w-3.5" /> {cafe.area}</p><p className="mt-2 flex items-center gap-1.5 text-xs text-[#88776d]"><Clock3 className="h-3.5 w-3.5" /> مفتوح اليوم · {cafe.time}</p><div className="mt-5 flex gap-2"><Link href="/restaurant/masaa" className="flex-1 rounded-xl bg-[#241c19] px-3 py-3 text-center text-xs font-black text-white">فتح المنيو</Link><button className="rounded-xl border border-[#dfcfc2] px-4 py-3 text-xs font-black text-[#684b3b]">حجز</button></div></div></article>)}</div></section>
    <section id="how" className="border-t border-[#eadfd4] bg-white px-5 py-16"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-black text-[#b66f45]">تجربة بدون تعقيد</p><h2 className="mt-2 text-3xl font-black">من الاكتشاف إلى طلبك</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{ n: "01", title: "اختر المقهى", body: "قارن المقاهي حسب الموقع والتقييم وأوقات العمل." }, { n: "02", title: "تصفح المنيو", body: "شاهد الأصناف والأسعار والصور قبل اتخاذ القرار." }, { n: "03", title: "اطلب أو احجز", body: "أكمل طلبك أو احجز جلستك بخطوات قليلة." }].map((step) => <div key={step.n} className="rounded-3xl border border-[#eadfd4] bg-[#fffdf9] p-6"><span className="text-3xl font-black text-[#e2b083]">{step.n}</span><h3 className="mt-5 text-lg font-black">{step.title}</h3><p className="mt-2 text-sm leading-7 text-[#88776d]">{step.body}</p></div>)}</div></div></section>
    <footer className="bg-[#241c19] px-5 py-8 text-center text-sm text-white/60"><p><span className="font-black text-[#f4b36a]">مقاهي المساء</span> · صفحة ديمو عامة لمنصة NFOOD</p></footer>
  </main>;
}
